version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: namstore-yubal_server_1
      APP_PORT: 8000
    depends_on:
      - server

  server:
    image: ghcr.io/guillevc/yubal:latest
    restart: unless-stopped
    init: true
    environment:
      PUID: "1000"
      PGID: "1000"
      YUBAL_SCHEDULER_CRON: "0 0 * * *"
      YUBAL_DOWNLOAD_UGC: "true"
      YUBAL_TZ: ${TZ:-Australia/Melbourne}
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/config:/app/config
