version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: metube_metube_1
      APP_PORT: 8081
    container_name: metube_app_proxy_1
  metube:
    image: >-
      ghcr.io/alexta69/metube:2026.06.06@sha256:acf201148260de39b7eeb316f3cd611088e4a707ff4a3f1ebf460fa72054c6e5
    restart: on-failure
    volumes:
      - ${UMBREL_ROOT}/home/Downloads/music:/music
    environment:
      - PUID=1000
      - PGID=1000
      - DELETE_FILE_ON_TRASHCAN=true
    container_name: metube_metube_1
