version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: namstore-upsnap_upsnap_1
      APP_PORT: 8090
    depends_on:
      - upsnap

  upsnap:
    image: ghcr.io/seriousm4x/upsnap:5
    user: "1000:1000"
    init: true
    cap_add:
      - NET_RAW
    cap_drop:
      - ALL
    volumes:
      - ./data:/app/pb_data
    environment:
      - UPSNAP_HTTP_LISTEN=0.0.0.0:8090
