services:
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 8001
    depends_on:
      - web

  web:
    image: jms1717/8mblocal:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/uploads:/app/uploads
      - ${APP_DATA_DIR}/outputs:/app/outputs
    environment:
      AUTH_ENABLED: "false"
      FILE_RETENTION_HOURS: "1"
      WORKER_CONCURRENCY: "1"
