services:
  app_proxy:
    environment:
      APP_HOST: mazanoke
      APP_PORT: 80
    depends_on:
      - mazanoke

  mazanoke:
    image: ghcr.io/civilblur/mazanoke:latest
    restart: unless-stopped
