services:
  gonic:
    image: sentriz/gonic:latest
    container_name: gonic
    environment:
      - TZ=Australia/Melbourne
      - GONIC_ADMIN_PASSWORD=${GONIC_ADMIN_PASSWORD}
      - GONIC_MUSIC_PATH=/music
      - GONIC_PODCAST_PATH=/podcasts
      - GONIC_PLAYLISTS_PATH=/playlists
      - GONIC_DB_PATH=/data/gonic.db
      - GONIC_CACHE_PATH=/data/cache
    ports:
      - "4747:80"
    volumes:
      - ./data:/data
      - ${UMBREL_ROOT}/home/Downloads/music:/music
      - ./podcasts:/podcasts
      - ./playlists:/playlists
    restart: unless-stopped